version: '3'

includes:
  common:
    taskfile: ./common/Taskfile.yml
    dir: ./common

tasks:
  build:target:
    dir: ..
    cmds:
      - docker build --build-arg WORKSPACE={{.PROJECT}} -t poe-accountant-{{.PROJECT}}:latest -f ./projects/yarn.Dockerfile .

  build:ninja-server:
    cmds:
      - task: build:target
        vars:
          PROJECT: ninja-server

  build:api-service:
    cmds:
      - task: build:target
        vars:
          PROJECT: api-service

  build:frontend:
    cmds:
      - task: build:target
        vars:
          PROJECT: frontend

  build:
    deps: [build:ninja-server, build:api-service, build:frontend]
    cmds:
      - echo "✅ All Docker images built successfully!"


  deploy:
    desc: Build, login, and push all images to registry
    deps: [login:registry, push:registry]
    cmds:
      - echo "✅ Complete deployment pipeline finished!"
