version: '3'

dotenv: ['.env.local', '.env']

includes:
  infrastructure:remote:
    taskfile: ./infrastructure/Taskfile.remote.yml
    dir: .
  infrastructure:local:
    taskfile: ./infrastructure/Taskfile.local.yml
    dir: .
  remote:terraform:
    taskfile: ./infrastructure/terraform/Taskfile.yml
    dir: .
  docker:
    taskfile: ./Taskfile.docker.yml
    dir: .

tasks:
  install:
    desc: Run yarn install
    cmds:
      - yarn install

  start:
    desc: Run yarn start
    cmds:
      - yarn start

  test:
    desc: Run yarn test
    cmds:
      - yarn test

  lint:
    desc: Run yarn lint
    cmds:
      - yarn lint

  setup-env:
    desc: Set up environment variables
    cmds:
      - ./scripts/setup-env.sh
