version: '3'

dotenv: ['.env.local', '.env']

includes:
  remote:
    taskfile: ./infrastructure/Taskfile.remote.yml
    dir: ./infrastructure
  local:
    taskfile: ./infrastructure/Taskfile.local.yml
    dir: ./infrastructure
  projects:
    taskfile: ./projects/Taskfile.yml
    dir: ./projects

tasks:
  install:
    desc: Run yarn install
    cmds:
      - yarn install

  start:
    desc: Run yarn start
    cmds:
      - yarn start

  test:
    desc: Run yarn test
    cmds:
      - yarn test

  lint:
    desc: Run yarn lint
    cmds:
      - yarn lint

  setup-env:
    desc: Set up environment variables
    cmds:
      - ./scripts/setup-env.sh

  start-local:
    desc: Start local infrastructure and deploy to local Kubernetes
    cmds:
      - task: infrastructure:local:start
      - echo "✅ Local environment is up and running!"
