version: '3'

tasks:
  provision:
    desc: Create and start local Redis and PostgreSQL containers
    cmds:
      - echo "🐳 Creating local infrastructure with Docker Compose..."
      - docker compose up -d
      - echo "✅ Local infrastructure provisioned!"
      - echo ""

  setup:
    dir: '{{.TASKFILE_DIR}}'
    desc: Setup connection to existing local infrastructure
    cmds:
      - ./scripts/configure-local-kubectl.sh

  start:
    desc: Start local Redis and PostgreSQL containers
    deps: [setup]
    cmds:
      - echo "🐳 Starting local infrastructure with Docker Compose..."
      - docker compose up -d
      - echo ""
      - echo "⏳ Waiting for services to be healthy..."
      - task: wait-for-health
      - echo ""
      - echo "✅ Local managed services started."
      - task docker:build:all
      - echo ""
      - echo "Deploying to k8s"
      - echo "📦 Updating Helm dependencies..."
      - helm dependency update ./infrastructure/helm
      - echo "🚀 Installing/upgrading Helm chart..."
      - |
        helm upgrade --install poe-accountant ./infrastructure/helm \
          --namespace poe-accountant \
          --create-namespace \
          --values ./infrastructure/helm/values.yaml \
          --wait \
          --debug

  stop:
    desc: Stop local Redis and PostgreSQL containers
    cmds:
      - echo "🛑 Stopping local infrastructure..."
      - echo "🗑️ Uninstalling Helm deployment..."
      - helm uninstall poe-accountant --namespace poe-accountant || echo "⚠️ Helm deployment not found or already uninstalled"
      - echo "🛑 Stopping Docker containers..."
      - docker compose stop
      - echo "✅ Local infrastructure stopped!"

  restart:
    desc: Restart local infrastructure
    cmds:
      - echo "🔄 Restarting local infrastructure..."
      - docker compose restart
      - echo ""
      - echo "⏳ Waiting for services to be healthy..."
      - task: wait-for-health
      - echo ""
      - echo "✅ Local infrastructure restarted!"
      - task: status

  status:
    desc: Show status of local infrastructure containers
    cmds:
      - |
        echo "📊 Local Infrastructure Status"
        echo "=============================="
        docker compose ps
        echo ""
        echo "🔌 Connection Details:"
        echo "PostgreSQL: postgresql://${LOCAL_POSTGRES_USER:-poe_user}:${LOCAL_POSTGRES_PASSWORD:-poe_password}@localhost:${LOCAL_POSTGRES_PORT:-5432}/${LOCAL_POSTGRES_DB:-poe_accountant}"
        echo "Redis:      redis://localhost:${LOCAL_REDIS_PORT:-6379}"

  url:
    desc: Show application URLs and how to access the services
    cmds:
      - |
        echo "🌐 Application URLs"
        echo "=================="
        echo ""
        
        # Get ingress controller service details
        INGRESS_HOST=$(kubectl get service poe-accountant-ingress-nginx-controller -n poe-accountant -o jsonpath='{.status.loadBalancer.ingress[0].ip}{.status.loadBalancer.ingress[0].hostname}')
        INGRESS_PORT=$(kubectl get service poe-accountant-ingress-nginx-controller -n poe-accountant -o jsonpath='{.spec.ports[?(@.name=="http")].port}')
        HTTPS_PORT=$(kubectl get service poe-accountant-ingress-nginx-controller -n poe-accountant -o jsonpath='{.spec.ports[?(@.name=="https")].port}')
        
        # Fallback to localhost and standard ports if not available
        if [ -z "$INGRESS_HOST" ]; then
          INGRESS_HOST="localhost"
        fi
        if [ -z "$INGRESS_PORT" ]; then
          INGRESS_PORT="80"
        fi
        if [ -z "$HTTPS_PORT" ]; then
          HTTPS_PORT="443"
        fi
        
        echo "🚀 Main Application:"
        echo "   Base URL: http://$INGRESS_HOST:$INGRESS_PORT"
        echo "   Secure URL: https://$INGRESS_HOST:$HTTPS_PORT"
        echo ""
        echo "🔧 API Endpoints:"
        echo "   Ninja API: http://$INGRESS_HOST:$INGRESS_PORT/api"
        echo "   Health Check: http://$INGRESS_HOST:$INGRESS_PORT/api/health"
        echo ""
        echo "📊 Infrastructure Services:"
        echo "   PostgreSQL: postgresql://${LOCAL_POSTGRES_USER:-poe_user}:${LOCAL_POSTGRES_PASSWORD:-poe_password}@localhost:${LOCAL_POSTGRES_PORT:-5432}/${LOCAL_POSTGRES_DB:-poe_accountant}"
        echo "   Redis: redis://localhost:${LOCAL_REDIS_PORT:-6379}"
        echo ""
        echo "🔍 Kubernetes Resources:"
        echo "   Namespace: poe-accountant"
        echo "   Ingress Controller: $INGRESS_HOST (HTTP: $INGRESS_PORT, HTTPS: $HTTPS_PORT)"
        echo ""
        echo "💡 Tip: Use 'kubectl get services -n poe-accountant' to see all service details"

  logs:
    desc: "Show logs for local infrastructure (usage: task infrastructure:local:logs -- [postgres|redis])"
    cmds:
      - |
        if [ "{{.CLI_ARGS}}" = "postgres" ]; then
          docker compose logs -f postgres
        elif [ "{{.CLI_ARGS}}" = "redis" ]; then
          docker compose logs -f redis
        else
          docker compose logs --tail=20
        fi

  destroy:
    desc: Destroy local infrastructure containers and volumes
    prompt: Are you sure you want to remove all local infrastructure data?
    cmds:
      - echo "💥 Destroying local infrastructure..."
      - docker compose down -v --remove-orphans
      - echo "💀 Local infrastructure destroyed!"

  validate:
    desc: Validate local infrastructure configuration
    cmds:
      - echo "✅ Validating local infrastructure..."
      - echo ""
      - echo "🔍 Docker Compose validation:"
      - docker compose config --quiet
      - echo "✅ Docker Compose configuration is valid!"
      - echo ""
      - echo "🔍 Testing connections:"
      - task: test-connections
      - echo ""
      - echo "✅ Local infrastructure validation complete!"

  pull:
    desc: Pull latest images for local infrastructure
    cmds:
      - echo "📥 Pulling latest Docker images..."
      - docker compose pull
      - echo "✅ Images updated!"

  build:
    desc: Build/rebuild local infrastructure containers
    cmds:
      - echo "🔨 Building local infrastructure..."
      - docker compose build
      - echo "✅ Build complete!"

  postgres-shell:
    desc: Connect to PostgreSQL shell
    deps: [check-postgres-running]
    cmds:
      - docker compose exec postgres psql -U ${LOCAL_POSTGRES_USER:-poe_user} -d ${LOCAL_POSTGRES_DB:-poe_accountant}

  redis-cli:
    desc: Connect to Redis CLI
    deps: [check-redis-running]
    cmds:
      - docker compose exec redis redis-cli

  backup-postgres:
    desc: Backup PostgreSQL database
    deps: [check-postgres-running]
    cmds:
      - mkdir -p backups
      - |
        BACKUP_FILE="backups/postgres-backup-$(date +%Y%m%d-%H%M%S).sql"
        echo "💾 Creating PostgreSQL backup: $BACKUP_FILE"
        docker compose exec postgres pg_dump -U ${LOCAL_POSTGRES_USER} ${LOCAL_POSTGRES_DB} > "$BACKUP_FILE"
        echo "✅ Backup created: $BACKUP_FILE"

  restore-postgres:
    desc: "Restore PostgreSQL database from backup (usage: task infrastructure:local:restore-postgres -- <backup-file>)"
    deps: [check-postgres-running]
    cmds:
      - |
        if [ -z "{{.CLI_ARGS}}" ]; then
          echo "❌ Error: Please specify backup file"
          echo "   Usage: task infrastructure:local:restore-postgres -- <backup-file>"
          exit 1
        fi
        if [ ! -f "{{.CLI_ARGS}}" ]; then
          echo "❌ Error: Backup file not found: {{.CLI_ARGS}}"
          exit 1
        fi
        echo "🔄 Restoring PostgreSQL from: {{.CLI_ARGS}}"
        docker compose exec -T postgres psql -U ${LOCAL_POSTGRES_USER} -d ${LOCAL_POSTGRES_DB} < "{{.CLI_ARGS}}"
        echo "✅ Database restored!"

  check-postgres-running:
    desc: Check if PostgreSQL container is running
    internal: true
    cmds:
      - |
        if ! docker compose ps postgres | grep -q "Up"; then
          echo "❌ Error: PostgreSQL container is not running"
          echo "   Start it with: task infrastructure:local:start"
          exit 1
        fi
    silent: true

  check-redis-running:
    desc: Check if Redis container is running
    internal: true
    cmds:
      - |
        if ! docker compose ps redis | grep -q "Up"; then
          echo "❌ Error: Redis container is not running"
          echo "   Start it with: task infrastructure:local:start"
          exit 1
        fi
    silent: true

  test-connections:
    desc: Test connections to local infrastructure
    deps: [check-postgres-running, check-redis-running]
    cmds:
      - echo "🔍 Testing local infrastructure connections..."
      - echo ""
      - echo "📋 PostgreSQL connection test:"
      - docker compose exec postgres pg_isready -U ${LOCAL_POSTGRES_USER}
      - echo ""
      - echo "📋 Redis connection test:"
      - docker compose exec redis redis-cli ping
      - echo ""
      - echo "✅ All connections successful!"

  wait-for-health:
    desc: Wait for local infrastructure services to be healthy and ready
    internal: true
    cmds:
      - |
        echo "🔍 Waiting for PostgreSQL to be ready..."
        while ! docker compose exec postgres pg_isready -U ${LOCAL_POSTGRES_USER:-postgres} >/dev/null 2>&1; do
          echo "  ... PostgreSQL not ready yet, waiting 2 seconds"
          sleep 2
        done
        echo "✅ PostgreSQL is ready!"
        
        echo "🔍 Waiting for Redis to be ready..."
        while ! docker compose exec valkey redis-cli ping >/dev/null 2>&1; do
          echo "  ... Redis not ready yet, waiting 2 seconds"
          sleep 2
        done
        echo "✅ Redis is ready!"
        
        echo "🔍 Verifying services are healthy..."
        until ! docker compose ps --format "table {{.Name}}\t{{.Status}}" | grep -E "(healthy|Up)" | wc -l | grep -q "2"; do
          echo "  ... Services still starting, waiting 2 seconds"
          sleep 2
        done
        echo "✅ All services are healthy!"
